### ISSUE TITLE
Adding propTypes to React components

### ISSUE THREAD

**Issue by jbranchaud** [dillonhafer/budgetal#4]
I've found it useful when developing React components to define `propTypes`. It serves as documentation and react is able to use the `propTypes` to provide warnings during development. It looks like there are some opportunities here to add `propTypes` to existing components.

https://facebook.github.io/react/docs/reusable-components.html

**Comment by dillonhafer** [comment]
This was actually on my radar, thanks for opening the issue. I think we should go ahead with it.

**Comment by dillonhafer** [comment]
Proptypes is no longer a thing, I was waiting two years until prop types was removed from react so I could close this issue without doing anything. 😉
