### ISSUE TITLE
Monthly overview not updated

### ISSUE THREAD

**Issue by dillonhafer** [dillonhafer/budgetal#6]
The monthly overview meter is not updated when budget item expenses are added/updated/deleted.

**Comment by jbranchaud** [comment]
I'm pretty sure at least part of the bug is in this file -- https://github.com/dillonhafer/budgetal/blob/master/app/assets/javascripts/components/Budgets/budget_form.js.jsx

**Comment by jbranchaud** [comment]
I'll take a stab at fixing this.

**Comment by dillonhafer** [comment]
Thank you! 💚

**Comment by dillonhafer** [comment]
This issue appears to be resolved :confused:

**Comment by jbranchaud** [comment]
Glad it resolved itself. When I was last looking at it, I got caught up in overcomplicating the fix.
